services:
  wiki-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      WIKI_ROOT: /app/wiki
    volumes:
      - /home/ubuntu/wiki:/app/wiki
    restart: unless-stopped
    ports:
      - "3002:3001"
